version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
    networks:
      - common-network
  mysql-container:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - /Users/boen/mysql-data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=score"
      - "TZ=Asia/Shanghai"
    networks:
      - common-network
  redis-container:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /Users/boen/redis-data:/data
      - /Users/boen/redis-config/redis.conf
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
