export const USER_CONFLICT = '用户已存在'
export const USER_NOT_FOUND = '用户未找到'
export const INCORRECT_PASSWORD = '密码不正确'
export const INVALID_TOKEN = '无效的token'
export const INVALID_PASSWORD = '无效的密码'
export const NO_TOKEN_PROVIDED = '没有token'
export const SESSION_NOT_FOUND = 'session未找到'
